# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=25)),
                ('enquiry', models.TextField(null=True)),
            ],
        ),
    ]
