# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20170611_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='lname',
            new_name='sname',
        ),
    ]
