# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20170612_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='fname',
            new_name='name',
        ),
    ]
