# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_auto_20170619_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='name',
            new_name='fname',
        ),
    ]
