# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_auto_20170619_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='fname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry',
            field=models.TextField(default=''),
        ),
    ]
